sudo: required

services:
  - docker

language: node_js

node_js: 10

cache: npm

script:
  - npm run coverage

before_deploy:
  - docker build . -t robertstettner/drone-quay

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
